// GENERATED by scripts/generate-theme-tokens.mjs — do not edit.
// Regenerate after changing the palette or roles in src/index.css:
//   npm run generate:tokens

export type Primitive = {
  name: string
  hex: string
  family: string
  shade: string
  isOverlay: boolean
}

export type Role = {
  name: string
  group: string
  /** The palette entry the locked dark value points at. */
  darkRef: string | null
  darkHex: string
}

export const PRIMITIVES: Primitive[] = [
  {
    "name": "--color-neutral-white",
    "hex": "#ffffffff",
    "family": "neutral",
    "shade": "white",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-black",
    "hex": "#000000ff",
    "family": "neutral",
    "shade": "black",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-50",
    "hex": "#fafafaff",
    "family": "neutral",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-100",
    "hex": "#f5f5f5ff",
    "family": "neutral",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-150",
    "hex": "#e5e5e5ff",
    "family": "neutral",
    "shade": "150",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-200",
    "hex": "#dbdbdbff",
    "family": "neutral",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-300",
    "hex": "#b5b5b5ff",
    "family": "neutral",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-400",
    "hex": "#7a7a7aff",
    "family": "neutral",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-500",
    "hex": "#5e5e5eff",
    "family": "neutral",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-600",
    "hex": "#4a4a4aff",
    "family": "neutral",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-700",
    "hex": "#363636ff",
    "family": "neutral",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-800",
    "hex": "#242424ff",
    "family": "neutral",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-900",
    "hex": "#121212ff",
    "family": "neutral",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-neutral-950",
    "hex": "#0a0a0aff",
    "family": "neutral",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-blue-50",
    "hex": "#f3f8fcff",
    "family": "blue",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-25",
    "hex": "#fafeffff",
    "family": "cyan",
    "shade": "25",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-50",
    "hex": "#e0fbffff",
    "family": "cyan",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-100",
    "hex": "#d5edf1ff",
    "family": "cyan",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-200",
    "hex": "#8af0ffff",
    "family": "cyan",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-300",
    "hex": "#5ceaffff",
    "family": "cyan",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-400",
    "hex": "#14e0ffff",
    "family": "cyan",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-500",
    "hex": "#00c1deff",
    "family": "cyan",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-600",
    "hex": "#00b1ccff",
    "family": "cyan",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-700",
    "hex": "#00a0b8ff",
    "family": "cyan",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-800",
    "hex": "#008ea3ff",
    "family": "cyan",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-900",
    "hex": "#005966ff",
    "family": "cyan",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-cyan-950",
    "hex": "#00353dff",
    "family": "cyan",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-blue-100",
    "hex": "#e3f1fdff",
    "family": "blue",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-blue-200",
    "hex": "#c8e2f9ff",
    "family": "blue",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-blue-300",
    "hex": "#94c7f0ff",
    "family": "blue",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-blue-400",
    "hex": "#6fb4eaff",
    "family": "blue",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-blue-500",
    "hex": "#3598e9ff",
    "family": "blue",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-blue-600",
    "hex": "#0072ceff",
    "family": "blue",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-blue-700",
    "hex": "#005aa3ff",
    "family": "blue",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-blue-800",
    "hex": "#00447aff",
    "family": "blue",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-blue-900",
    "hex": "#002d52ff",
    "family": "blue",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-blue-950",
    "hex": "#001629ff",
    "family": "blue",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-red-50",
    "hex": "#fcefeeff",
    "family": "red",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-red-100",
    "hex": "#f7d6d4ff",
    "family": "red",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-red-200",
    "hex": "#eea5a0ff",
    "family": "red",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-red-300",
    "hex": "#e77c74ff",
    "family": "red",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-red-400",
    "hex": "#df5349ff",
    "family": "red",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-red-500",
    "hex": "#d03025ff",
    "family": "red",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-red-600",
    "hex": "#ba2b21ff",
    "family": "red",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-red-700",
    "hex": "#a5261dff",
    "family": "red",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-red-800",
    "hex": "#8f2119ff",
    "family": "red",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-red-900",
    "hex": "#821e17ff",
    "family": "red",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-red-950",
    "hex": "#45100cff",
    "family": "red",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-orange-50",
    "hex": "#fdf3edff",
    "family": "orange",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-orange-100",
    "hex": "#fae4d6ff",
    "family": "orange",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-orange-200",
    "hex": "#f4bc9aff",
    "family": "orange",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-orange-300",
    "hex": "#ef9e6cff",
    "family": "orange",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-orange-400",
    "hex": "#ea803eff",
    "family": "orange",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-orange-500",
    "hex": "#dc6418ff",
    "family": "orange",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-orange-600",
    "hex": "#c55916ff",
    "family": "orange",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-orange-700",
    "hex": "#af4f13ff",
    "family": "orange",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-orange-800",
    "hex": "#a14811ff",
    "family": "orange",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-orange-900",
    "hex": "#7c370dff",
    "family": "orange",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-orange-950",
    "hex": "#4a2108ff",
    "family": "orange",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-50",
    "hex": "#fffcf0ff",
    "family": "yellow",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-100",
    "hex": "#fff9e0ff",
    "family": "yellow",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-200",
    "hex": "#ffefadff",
    "family": "yellow",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-300",
    "hex": "#ffe785ff",
    "family": "yellow",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-400",
    "hex": "#ffde5cff",
    "family": "yellow",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-500",
    "hex": "#f5c400ff",
    "family": "yellow",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-600",
    "hex": "#dbaf00ff",
    "family": "yellow",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-700",
    "hex": "#c7a000ff",
    "family": "yellow",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-800",
    "hex": "#b28f00ff",
    "family": "yellow",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-900",
    "hex": "#665200ff",
    "family": "yellow",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-yellow-950",
    "hex": "#3d3100ff",
    "family": "yellow",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-green-50",
    "hex": "#effbf3ff",
    "family": "green",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-green-100",
    "hex": "#d6f5e0ff",
    "family": "green",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-green-200",
    "hex": "#9de7b6ff",
    "family": "green",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-green-300",
    "hex": "#7cde9dff",
    "family": "green",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-green-400",
    "hex": "#47d175ff",
    "family": "green",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-green-500",
    "hex": "#30c060ff",
    "family": "green",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-green-600",
    "hex": "#2bab56ff",
    "family": "green",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-green-700",
    "hex": "#279b4eff",
    "family": "green",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-green-800",
    "hex": "#228743ff",
    "family": "green",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-teal-50",
    "hex": "#e5fbf7ff",
    "family": "teal",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-green-900",
    "hex": "#15562bff",
    "family": "green",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-green-950",
    "hex": "#0c3119ff",
    "family": "green",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-teal-100",
    "hex": "#dcf9f4ff",
    "family": "teal",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-teal-200",
    "hex": "#91eddcff",
    "family": "teal",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-teal-300",
    "hex": "#72e8d3ff",
    "family": "teal",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-teal-400",
    "hex": "#39dfc1ff",
    "family": "teal",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-teal-500",
    "hex": "#22d3b2ff",
    "family": "teal",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-teal-600",
    "hex": "#1ebda0ff",
    "family": "teal",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-teal-700",
    "hex": "#1cb095ff",
    "family": "teal",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-teal-800",
    "hex": "#199a82ff",
    "family": "teal",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-teal-900",
    "hex": "#0f5c4eff",
    "family": "teal",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-teal-950",
    "hex": "#072c25ff",
    "family": "teal",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-purple-50",
    "hex": "#ede7f8ff",
    "family": "purple",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-purple-100",
    "hex": "#dbcff2ff",
    "family": "purple",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-purple-200",
    "hex": "#bca7e7ff",
    "family": "purple",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-purple-300",
    "hex": "#9e7fdcff",
    "family": "purple",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-purple-400",
    "hex": "#7f57d1ff",
    "family": "purple",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-purple-500",
    "hex": "#6335c0ff",
    "family": "purple",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-purple-600",
    "hex": "#572ea8ff",
    "family": "purple",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-purple-700",
    "hex": "#4e2a98ff",
    "family": "purple",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-purple-800",
    "hex": "#422380ff",
    "family": "purple",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-pink-50",
    "hex": "#fbe5f3ff",
    "family": "pink",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-purple-900",
    "hex": "#301b60ff",
    "family": "purple",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-purple-950",
    "hex": "#100920ff",
    "family": "purple",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-violet-50",
    "hex": "#f5f3ff",
    "family": "violet",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-violet-100",
    "hex": "#ede9fe",
    "family": "violet",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-violet-200",
    "hex": "#ddd6fe",
    "family": "violet",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-violet-300",
    "hex": "#c4b5fd",
    "family": "violet",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-violet-400",
    "hex": "#a78bfa",
    "family": "violet",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-violet-500",
    "hex": "#8b5cf6",
    "family": "violet",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-violet-600",
    "hex": "#7c3aed",
    "family": "violet",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-violet-700",
    "hex": "#6d28d9",
    "family": "violet",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-violet-800",
    "hex": "#5b21b6",
    "family": "violet",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-violet-900",
    "hex": "#4c1d95",
    "family": "violet",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-violet-950",
    "hex": "#2e1065",
    "family": "violet",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-pink-100",
    "hex": "#f4bee1ff",
    "family": "pink",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-pink-200",
    "hex": "#eea0d4ff",
    "family": "pink",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-pink-300",
    "hex": "#e363b9ff",
    "family": "pink",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-pink-400",
    "hex": "#dd3ca7ff",
    "family": "pink",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-pink-500",
    "hex": "#d02597ff",
    "family": "pink",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-pink-600",
    "hex": "#ad1f7eff",
    "family": "pink",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-pink-700",
    "hex": "#981b6eff",
    "family": "pink",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-pink-800",
    "hex": "#82175eff",
    "family": "pink",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-pink-900",
    "hex": "#68124bff",
    "family": "pink",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-pink-950",
    "hex": "#340926ff",
    "family": "pink",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-50",
    "hex": "#ebf3ff",
    "family": "z-blue",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-100",
    "hex": "#c2dbff",
    "family": "z-blue",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-200",
    "hex": "#8fbdff",
    "family": "z-blue",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-300",
    "hex": "#5c9fff",
    "family": "z-blue",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-400",
    "hex": "#0c69ed",
    "family": "z-blue",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-500",
    "hex": "#0058d6",
    "family": "z-blue",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-600",
    "hex": "#004dbc",
    "family": "z-blue",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-700",
    "hex": "#003d94",
    "family": "z-blue",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-800",
    "hex": "#00327a",
    "family": "z-blue",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-900",
    "hex": "#00265c",
    "family": "z-blue",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-z-blue-950",
    "hex": "#0c1727",
    "family": "z-blue",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-50",
    "hex": "#eef2ff",
    "family": "indigo",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-100",
    "hex": "#e0e7ff",
    "family": "indigo",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-200",
    "hex": "#c7d2fe",
    "family": "indigo",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-300",
    "hex": "#a5b4fc",
    "family": "indigo",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-400",
    "hex": "#818cf8",
    "family": "indigo",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-500",
    "hex": "#6366f1",
    "family": "indigo",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-600",
    "hex": "#4f46e5",
    "family": "indigo",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-700",
    "hex": "#4338ca",
    "family": "indigo",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-800",
    "hex": "#3730a3",
    "family": "indigo",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-900",
    "hex": "#312e81",
    "family": "indigo",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-indigo-950",
    "hex": "#1e1b4b",
    "family": "indigo",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-midnight-700",
    "hex": "#201c3d",
    "family": "midnight",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-midnight-800",
    "hex": "#1a1548",
    "family": "midnight",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-midnight-900",
    "hex": "#131032",
    "family": "midnight",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-midnight-950",
    "hex": "#0c0b1c",
    "family": "midnight",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-50",
    "hex": "#f0f1fd",
    "family": "z-violet",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-100",
    "hex": "#e4e6fb",
    "family": "z-violet",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-200",
    "hex": "#cfd2f6ff",
    "family": "z-violet",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-300",
    "hex": "#b1b4f0ff",
    "family": "z-violet",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-400",
    "hex": "#9491e8ff",
    "family": "z-violet",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-500",
    "hex": "#8176deff",
    "family": "z-violet",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-600",
    "hex": "#715ccfff",
    "family": "z-violet",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-700",
    "hex": "#624cb6ff",
    "family": "z-violet",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-800",
    "hex": "#504093ff",
    "family": "z-violet",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-900",
    "hex": "#433976ff",
    "family": "z-violet",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--color-z-violet-950",
    "hex": "#1e1933ff",
    "family": "z-violet",
    "shade": "950",
    "isOverlay": false
  },
  {
    "name": "--color-dark-50",
    "hex": "#ffffff",
    "family": "dark",
    "shade": "50",
    "isOverlay": false
  },
  {
    "name": "--color-dark-100",
    "hex": "#e6e5f7",
    "family": "dark",
    "shade": "100",
    "isOverlay": false
  },
  {
    "name": "--color-dark-200",
    "hex": "#a7a3cb",
    "family": "dark",
    "shade": "200",
    "isOverlay": false
  },
  {
    "name": "--color-dark-300",
    "hex": "#7f57d1",
    "family": "dark",
    "shade": "300",
    "isOverlay": false
  },
  {
    "name": "--color-dark-400",
    "hex": "#562ea7",
    "family": "dark",
    "shade": "400",
    "isOverlay": false
  },
  {
    "name": "--color-dark-500",
    "hex": "#3e3c62",
    "family": "dark",
    "shade": "500",
    "isOverlay": false
  },
  {
    "name": "--color-dark-600",
    "hex": "#29274d",
    "family": "dark",
    "shade": "600",
    "isOverlay": false
  },
  {
    "name": "--color-dark-700",
    "hex": "#201d3b",
    "family": "dark",
    "shade": "700",
    "isOverlay": false
  },
  {
    "name": "--color-dark-800",
    "hex": "#121129",
    "family": "dark",
    "shade": "800",
    "isOverlay": false
  },
  {
    "name": "--color-dark-900",
    "hex": "#0f0c17",
    "family": "dark",
    "shade": "900",
    "isOverlay": false
  },
  {
    "name": "--overlay-dark-subtle",
    "hex": "#00000029",
    "family": "dark",
    "shade": "subtle",
    "isOverlay": true
  },
  {
    "name": "--overlay-dark-default",
    "hex": "#00000033",
    "family": "dark",
    "shade": "default",
    "isOverlay": true
  },
  {
    "name": "--overlay-dark-light",
    "hex": "#0000003d",
    "family": "dark",
    "shade": "light",
    "isOverlay": true
  },
  {
    "name": "--overlay-dark-medium",
    "hex": "#00000052",
    "family": "dark",
    "shade": "medium",
    "isOverlay": true
  },
  {
    "name": "--overlay-dark-heavy",
    "hex": "#0000007a",
    "family": "dark",
    "shade": "heavy",
    "isOverlay": true
  },
  {
    "name": "--overlay-dark-strong",
    "hex": "#000000a6",
    "family": "dark",
    "shade": "strong",
    "isOverlay": true
  },
  {
    "name": "--overlay-light-subtle",
    "hex": "#ffffff29",
    "family": "light",
    "shade": "subtle",
    "isOverlay": true
  },
  {
    "name": "--overlay-light-light",
    "hex": "#ffffff3d",
    "family": "light",
    "shade": "light",
    "isOverlay": true
  },
  {
    "name": "--overlay-light-medium",
    "hex": "#ffffff52",
    "family": "light",
    "shade": "medium",
    "isOverlay": true
  },
  {
    "name": "--overlay-light-heavy",
    "hex": "#ffffff7a",
    "family": "light",
    "shade": "heavy",
    "isOverlay": true
  },
  {
    "name": "--overlay-light-strong",
    "hex": "#ffffffa6",
    "family": "light",
    "shade": "strong",
    "isOverlay": true
  },
  {
    "name": "--color-special-content-pack-bg",
    "hex": "#ebd47b",
    "family": "special-content-pack-bg",
    "shade": "",
    "isOverlay": false
  }
]

export const ROLES: Role[] = [
  {
    "name": "--color-bg-accent-teal-subtle-pressed",
    "group": "bg",
    "darkRef": "--color-teal-200",
    "darkHex": "#91eddcff"
  },
  {
    "name": "--color-bg-action-brand-pressed",
    "group": "bg",
    "darkRef": "--color-z-blue-800",
    "darkHex": "#00327a"
  },
  {
    "name": "--color-bg-action-inverse-disabled",
    "group": "bg",
    "darkRef": "--color-neutral-700",
    "darkHex": "#363636ff"
  },
  {
    "name": "--color-bg-action-primary-default",
    "group": "bg",
    "darkRef": "--color-dark-400",
    "darkHex": "#562ea7"
  },
  {
    "name": "--color-bg-action-primary-disabled",
    "group": "bg",
    "darkRef": "--color-neutral-700",
    "darkHex": "#363636ff"
  },
  {
    "name": "--color-bg-action-primary-hover",
    "group": "bg",
    "darkRef": "--color-dark-300",
    "darkHex": "#7f57d1"
  },
  {
    "name": "--color-bg-action-primary-selected",
    "group": "bg",
    "darkRef": "--color-dark-600",
    "darkHex": "#29274d"
  },
  {
    "name": "--color-bg-action-secondary-default",
    "group": "bg",
    "darkRef": "--color-dark-700",
    "darkHex": "#201d3b"
  },
  {
    "name": "--color-bg-action-secondary-hover",
    "group": "bg",
    "darkRef": "--color-dark-300",
    "darkHex": "#7f57d1"
  },
  {
    "name": "--color-bg-action-secondary-pressed",
    "group": "bg",
    "darkRef": "--color-purple-600",
    "darkHex": "#572ea8ff"
  },
  {
    "name": "--color-bg-action-tertiary-hover",
    "group": "bg",
    "darkRef": "--color-neutral-100",
    "darkHex": "#f5f5f5ff"
  },
  {
    "name": "--color-bg-overlay-default",
    "group": "bg",
    "darkRef": "--overlay-dark-medium",
    "darkHex": "#00000052"
  },
  {
    "name": "--color-bg-overlay-light-medium",
    "group": "bg",
    "darkRef": "--overlay-light-medium",
    "darkHex": "#ffffff52"
  },
  {
    "name": "--color-bg-overlay-modal",
    "group": "bg",
    "darkRef": "--overlay-dark-default",
    "darkHex": "#00000033"
  },
  {
    "name": "--color-bg-skeleton",
    "group": "bg",
    "darkRef": "--overlay-dark-subtle",
    "darkHex": "#00000029"
  },
  {
    "name": "--color-bg-skeleton-inverse",
    "group": "bg",
    "darkRef": "--overlay-light-subtle",
    "darkHex": "#ffffff29"
  },
  {
    "name": "--color-bg-surface-active",
    "group": "bg",
    "darkRef": "--color-dark-500",
    "darkHex": "#3e3c62"
  },
  {
    "name": "--color-bg-surface-brand-default",
    "group": "bg",
    "darkRef": "--color-dark-400",
    "darkHex": "#562ea7"
  },
  {
    "name": "--color-bg-surface-brand-subtle",
    "group": "bg",
    "darkRef": "--color-dark-700",
    "darkHex": "#201d3b"
  },
  {
    "name": "--color-bg-surface-default",
    "group": "bg",
    "darkRef": "--color-dark-800",
    "darkHex": "#121129"
  },
  {
    "name": "--color-bg-surface-form",
    "group": "bg",
    "darkRef": "--color-dark-700",
    "darkHex": "#201d3b"
  },
  {
    "name": "--color-bg-surface-hover",
    "group": "bg",
    "darkRef": "--color-dark-600",
    "darkHex": "#29274d"
  },
  {
    "name": "--color-bg-surface-inverse-default",
    "group": "bg",
    "darkRef": "--color-neutral-900",
    "darkHex": "#121212ff"
  },
  {
    "name": "--color-bg-surface-inverse-hover",
    "group": "bg",
    "darkRef": "--color-purple-100",
    "darkHex": "#dbcff2ff"
  },
  {
    "name": "--color-bg-surface-selected",
    "group": "bg",
    "darkRef": "--color-dark-600",
    "darkHex": "#29274d"
  },
  {
    "name": "--color-bg-surface-status-negative-strong",
    "group": "bg",
    "darkRef": "--color-red-100",
    "darkHex": "#f7d6d4ff"
  },
  {
    "name": "--color-bg-surface-status-negative-subtle",
    "group": "bg",
    "darkRef": "--color-red-900",
    "darkHex": "#821e17ff"
  },
  {
    "name": "--color-bg-surface-status-warning-subtle",
    "group": "bg",
    "darkRef": "--color-orange-900",
    "darkHex": "#7c370dff"
  },
  {
    "name": "--color-bg-surface-strong",
    "group": "bg",
    "darkRef": "--color-dark-600",
    "darkHex": "#29274d"
  },
  {
    "name": "--color-bg-surface-subtle",
    "group": "bg",
    "darkRef": "--color-dark-700",
    "darkHex": "#201d3b"
  },
  {
    "name": "--color-border-action-primary-default",
    "group": "border",
    "darkRef": "--color-dark-300",
    "darkHex": "#7f57d1"
  },
  {
    "name": "--color-border-action-primary-focused",
    "group": "border",
    "darkRef": "--color-z-blue-300",
    "darkHex": "#5c9fff"
  },
  {
    "name": "--color-border-action-primary-selected",
    "group": "border",
    "darkRef": "--color-dark-400",
    "darkHex": "#562ea7"
  },
  {
    "name": "--color-border-action-secondary-default",
    "group": "border",
    "darkRef": "--color-dark-500",
    "darkHex": "#3e3c62"
  },
  {
    "name": "--color-border-action-secondary-focused",
    "group": "border",
    "darkRef": "--color-z-blue-300",
    "darkHex": "#5c9fff"
  },
  {
    "name": "--color-border-action-tertiary-hover",
    "group": "border",
    "darkRef": "--color-neutral-500",
    "darkHex": "#5e5e5eff"
  },
  {
    "name": "--color-border-action-tertiary-pressed",
    "group": "border",
    "darkRef": "--color-neutral-600",
    "darkHex": "#4a4a4aff"
  },
  {
    "name": "--color-border-input-active",
    "group": "border",
    "darkRef": "--color-dark-200",
    "darkHex": "#a7a3cb"
  },
  {
    "name": "--color-border-input-default",
    "group": "border",
    "darkRef": "--color-dark-600",
    "darkHex": "#29274d"
  },
  {
    "name": "--color-border-input-status-negative-strong",
    "group": "border",
    "darkRef": "--color-red-800",
    "darkHex": "#8f2119ff"
  },
  {
    "name": "--color-border-input-status-warning-strong",
    "group": "border",
    "darkRef": "--color-orange-300",
    "darkHex": "#ef9e6cff"
  },
  {
    "name": "--color-border-system-default",
    "group": "border",
    "darkRef": "--color-dark-500",
    "darkHex": "#3e3c62"
  },
  {
    "name": "--color-border-system-strong",
    "group": "border",
    "darkRef": "--color-dark-200",
    "darkHex": "#a7a3cb"
  },
  {
    "name": "--color-border-system-subtle",
    "group": "border",
    "darkRef": "--color-dark-600",
    "darkHex": "#29274d"
  },
  {
    "name": "--color-content-action-on-inverse-default",
    "group": "content",
    "darkRef": "--color-neutral-950",
    "darkHex": "#0a0a0aff"
  },
  {
    "name": "--color-content-action-on-primary-default",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-action-on-primary-disabled",
    "group": "content",
    "darkRef": "--color-neutral-500",
    "darkHex": "#5e5e5eff"
  },
  {
    "name": "--color-content-action-on-secondary-default",
    "group": "content",
    "darkRef": "--color-dark-100",
    "darkHex": "#e6e5f7"
  },
  {
    "name": "--color-content-action-on-secondary-inverse",
    "group": "content",
    "darkRef": "--color-neutral-white",
    "darkHex": "#ffffffff"
  },
  {
    "name": "--color-content-active",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-brand-default",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-disabled",
    "group": "content",
    "darkRef": "--color-neutral-500",
    "darkHex": "#5e5e5eff"
  },
  {
    "name": "--color-content-inverse-link-action-default",
    "group": "content",
    "darkRef": "--color-z-blue-400",
    "darkHex": "#0c69ed"
  },
  {
    "name": "--color-content-inverse-primary",
    "group": "content",
    "darkRef": "--color-neutral-white",
    "darkHex": "#ffffffff"
  },
  {
    "name": "--color-content-inverse-secondary",
    "group": "content",
    "darkRef": "--color-neutral-150",
    "darkHex": "#e5e5e5ff"
  },
  {
    "name": "--color-content-inverse-tertiary",
    "group": "content",
    "darkRef": "--color-neutral-200",
    "darkHex": "#dbdbdbff"
  },
  {
    "name": "--color-content-link-action-default",
    "group": "content",
    "darkRef": "--color-dark-200",
    "darkHex": "#a7a3cb"
  },
  {
    "name": "--color-content-link-action-hover",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-link-inline-default",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-on-brand-default",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-on-status-negative-strong",
    "group": "content",
    "darkRef": "--color-red-900",
    "darkHex": "#821e17ff"
  },
  {
    "name": "--color-content-on-status-negative-subtle",
    "group": "content",
    "darkRef": "--color-red-50",
    "darkHex": "#fcefeeff"
  },
  {
    "name": "--color-content-placeholder",
    "group": "content",
    "darkRef": "--color-dark-200",
    "darkHex": "#a7a3cb"
  },
  {
    "name": "--color-content-primary",
    "group": "content",
    "darkRef": "--color-dark-50",
    "darkHex": "#ffffff"
  },
  {
    "name": "--color-content-secondary",
    "group": "content",
    "darkRef": "--color-dark-100",
    "darkHex": "#e6e5f7"
  },
  {
    "name": "--color-content-status-info",
    "group": "content",
    "darkRef": "--color-z-blue-300",
    "darkHex": "#5c9fff"
  },
  {
    "name": "--color-content-status-negative",
    "group": "content",
    "darkRef": "--color-red-300",
    "darkHex": "#e77c74ff"
  },
  {
    "name": "--color-content-status-positive",
    "group": "content",
    "darkRef": "--color-green-500",
    "darkHex": "#30c060ff"
  },
  {
    "name": "--color-content-status-warning",
    "group": "content",
    "darkRef": "--color-yellow-500",
    "darkHex": "#f5c400ff"
  },
  {
    "name": "--color-content-tertiary",
    "group": "content",
    "darkRef": "--color-dark-200",
    "darkHex": "#a7a3cb"
  },
  {
    "name": "--color-special-label-application-bg",
    "group": "special",
    "darkRef": "--color-z-blue-950",
    "darkHex": "#0c1727"
  },
  {
    "name": "--color-special-label-application-border",
    "group": "special",
    "darkRef": "--color-z-blue-200",
    "darkHex": "#8fbdff"
  },
  {
    "name": "--color-special-label-application-text",
    "group": "special",
    "darkRef": "--color-z-blue-200",
    "darkHex": "#8fbdff"
  },
  {
    "name": "--color-special-label-lesson-bg",
    "group": "special",
    "darkRef": "--color-yellow-950",
    "darkHex": "#3d3100ff"
  },
  {
    "name": "--color-special-label-lesson-border",
    "group": "special",
    "darkRef": "--color-yellow-200",
    "darkHex": "#ffefadff"
  },
  {
    "name": "--color-special-label-lesson-text",
    "group": "special",
    "darkRef": "--color-yellow-200",
    "darkHex": "#ffefadff"
  }
]
